package io.github.ikunkk02.chatcanvas.voice;

public enum VoiceInputState {
	DISABLED,
	UNSUPPORTED_PLATFORM,
	MODEL_MISSING,
	MODEL_DOWNLOADING,
	MODEL_VERIFYING,
	MODEL_EXTRACTING,
	MODEL_LOADING,
	IDLE,
	LISTENING,
	RECOGNIZING,
	COMPLETED,
	CANCELLED,
	ERROR
}
